# Worksheet 3 — Verification of Unitarity of Quantum Gates

| Field | Details |
|---|---|
| **Name** | C S Deeraj |
| **Roll No.** | CH.SC.U4CSE24106 |
| **Worksheet No.** | 3 |
| **Serial No.** | 9 |
| **Date** | 07/09/2026 |
| **Course** | 23CSE463 — Quantum Computing |
| **Experiment Title** | Verification of Unitarity of Quantum Gates |

## Aim

To verify mathematically that the fundamental single-qubit quantum gate matrices are unitary using PennyLane and NumPy.

## Software / Tools Required

Python 3.10+, Jupyter Notebook, PennyLane, NumPy

## Procedure

1. Obtain the matrix representation of each fundamental gate.
2. For each matrix U, calculate its conjugate transpose U†.
3. Compute U†U.
4. Compare U†U with the identity matrix using NumPy.
5. Report whether each gate satisfies the unitarity condition.

## Code



In [1]:
import pennylane as qml
import numpy as np

gates = {
    "Identity": qml.Identity(0).matrix(),
    "Pauli-X": qml.PauliX(0).matrix(),
    "Pauli-Y": qml.PauliY(0).matrix(),
    "Pauli-Z": qml.PauliZ(0).matrix(),
    "S": qml.S(0).matrix(),
    "T": qml.T(0).matrix(),
    "Hadamard": qml.Hadamard(0).matrix(),
}

identity = np.eye(2)

for name, U in gates.items():
    product = U.conj().T @ U
    unitary = np.allclose(product, identity)

    print(f"\n{name}")
    print("U†U =")
    print(product)
    print("Unitary:", unitary)



Identity
U†U =
[[1. 0.]
 [0. 1.]]
Unitary: True

Pauli-X
U†U =
[[1 0]
 [0 1]]
Unitary: True

Pauli-Y
U†U =
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Unitary: True

Pauli-Z
U†U =
[[1 0]
 [0 1]]
Unitary: True

S
U†U =
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Unitary: True

T
U†U =
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Unitary: True

Hadamard
U†U =
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
Unitary: True


## Output / Observation

Run the code cells above to generate the actual output. The expected observation is:

For every listed gate, U†U is equal to the 2 × 2 identity matrix within numerical precision.

## Result

The unitarity of the fundamental single-qubit quantum gates was successfully verified.
